<!--footer start-->
<footer class="site-footer text-center">
    تصميم و تطوير<a href="http://www.tibadev.com" target="_blank">&nbsp;طيبة ديف للبرمجيات</a> 2017
    <a href="#" class="go-top">
        <i class="fa fa-angle-up"></i>
    </a>
</footer>
<!--footer end-->
</section>

<!-- js placed at the end of the document so the pages load faster -->
<script type="text/javascript"
        src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/jquery-ui-1.9.2.custom.min.js"; ?>></script>
<script type="text/javascript"
        src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/jquery.ui.touch-punch.min.js"; ?>></script>
<script class="include" type="text/javascript"
        src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/jquery.dcjqaccordion.2.7.js"; ?>></script>
<script type="text/javascript"
        src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/jquery.scrollTo.min.js"; ?>></script>
<script type="text/javascript" src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/jquery.nicescroll.js"; ?>></script>
<!--common script for all pages-->
<script type="text/javascript" src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/common-scripts.js"; ?>></script>
<!--script for this page-->
<script type="text/javascript"
        src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/jquery-ui-1.9.2.custom.min.js"; ?>></script>
<!--custom switch-->
<script type="text/javascript" src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/bootstrap-switch.js"; ?>></script>

<script type="text/javascript" src=<?php echo "/" . BASE_DIRECTORY . "/assets/js/main.js"; ?>></script>

</html>

<?php
// Close DB Connection
$conn = null;
?>
